apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "more-test-docs"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: docs
  owner: "group:default/backstage"
  lifecycle: experimental
  dependsOn: "resource:default/more-test-docs-database"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "more-test-docs-database"
spec:
  type: database
  owner: "group:default/backstage"
  lifecycle: experimental
